new.overdraft.limit=25000
standard.overdraft.limit=25000
premium.overdraft.limit=25000
privilege.overdraft.limit=25000
overdraft.multiplier=2.5
minimum.overdraft.limit=25000
daily.transfer.limit.new=100000
daily.transfer.limit.standard=500000
daily.transfer.limit.premium=1000000
