new.inactive.months=3
standard.inactive.months=3
premium.inactive.months=3
privilege.inactive.months=3
daily.transfer.limit.new=0
daily.transfer.limit.standard=0
daily.transfer.limit.premium=0
daily.transfer.limit.privilege=0